# Generated by Django 2.2.2 on 2019-06-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='todo_id',
        ),
    ]
