# Generated by Django 2.2.2 on 2019-06-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
